env: "local"
token_ttl: 3h
grpc:
  port: 9090
  timeout: 5h
database:
  host: "localhost"
  user: "fanfurick"
  password: ""
  dbname: "grpc"
  port: "5432"
  sslmode: "disable"
  time_zone: "Asia/Vladivostok"